### ISSUE TITLE
1.20.4 crash Apperance menu

### ISSUE THREAD

**Issue by Snaklilopin** [WildfireRomeo/WildfireFemaleGenderMod#168]
I think bc i very w man and use older build on newer version
so logs is 
---- Minecraft Crash Report ----
// Don't do that.

Time: 2023-12-10 19:04:50
Description: mouseClicked event handler

java.lang.IncompatibleClassChangeError: class com.wildfire.gui.WildfireBreastPresetList overrides final method net.minecraft.class_339.method_37020(Lnet/minecraft/class_6382;)V
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at com.wildfire.gui.screen.WildfireBreastCustomizationScreen.method_25426(WildfireBreastCustomizationScreen.java:133)
	at net.minecraft.class_437.method_25423(class_437.java:298)
	at net.minecraft.class_310.method_1507(class_310.java:1187)
	at com.wildfire.gui.screen.WardrobeBrowserScreen.lambda$init$1(WardrobeBrowserScreen.java:83)
	at net.minecraft.class_4185.method_25306(class_4185.java:95)
	at net.minecraft.class_4264.method_25348(class_4264.java:48)
	at net.minecraft.class_339.method_25402(class_339.java:145)
	at net.minecraft.class_4069.method_25402(class_4069.java:38)
	at net.minecraft.class_312.method_1611(class_312.java:99)
	at net.minecraft.class_437.method_25412(class_437.java:414)
	at net.minecraft.class_312.method_1601(class_312.java:99)
	at net.minecraft.class_312.method_22686(class_312.java:180)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.redirect$zog001$viafabricplus$storeEvent(class_312.java:1055)
	at net.minecraft.class_312.method_22684(class_312.java:180)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:1600)
	at net.minecraft.class_1041.method_15998(class_1041.java:1114)
	at net.minecraft.class_310.method_1523(class_310.java:1349)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at com.wildfire.gui.screen.WildfireBreastCustomizationScreen.method_25426(WildfireBreastCustomizationScreen.java:133)
	at net.minecraft.class_437.method_25423(class_437.java:298)
	at net.minecraft.class_310.method_1507(class_310.java:1187)
	at com.wildfire.gui.screen.WardrobeBrowserScreen.lambda$init$1(WardrobeBrowserScreen.java:83)
	at net.minecraft.class_4185.method_25306(class_4185.java:95)
	at net.minecraft.class_4264.method_25348(class_4264.java:48)
	at net.minecraft.class_339.method_25402(class_339.java:145)
	at net.minecraft.class_4069.method_25402(class_4069.java:38)
	at net.minecraft.class_312.method_1611(class_312.java:99)
	at net.minecraft.class_437.method_25412(class_437.java:414)
	at net.minecraft.class_312.method_1601(class_312.java:99)
	at net.minecraft.class_312.method_22686(class_312.java:180)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.redirect$zog001$viafabricplus$storeEvent(class_312.java:1055)
	at net.minecraft.class_312.method_22684(class_312.java:180)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:1600)

-- Affected screen --
Details:
	Screen name: com.wildfire.gui.screen.WardrobeBrowserScreen
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:414)
	at net.minecraft.class_312.method_1601(class_312.java:99)
	at net.minecraft.class_312.method_22686(class_312.java:180)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.redirect$zog001$viafabricplus$storeEvent(class_312.java:1055)
	at net.minecraft.class_312.method_22684(class_312.java:180)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:1600)
	at net.minecraft.class_1041.method_15998(class_1041.java:1114)
	at net.minecraft.class_310.method_1523(class_310.java:1349)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	
	
	AND A FILE LOGS IF IM MISS SMTHNG
	
[tl-logger7743203493044339794.txt](https://github.com/WildfireRomeo/WildfireFemaleGenderMod/files/13628449/tl-logger7743203493044339794.txt)
[crash-2023-12-10_19.04.50-client.txt](https://github.com/WildfireRomeo/WildfireFemaleGenderMod/files/13628452/crash-2023-12-10_19.04.50-client.txt)

**Comment by WildfireRomeo** [comment]
1.20.4 is not supported yet.
