### ISSUE TITLE
1.19.2 Crash on Female Hurt Sound

### ISSUE THREAD

**Issue by AzureMonument** [WildfireRomeo/WildfireFemaleGenderMod#78]
Was making a new modpack and decided to throw hands with a spider. Here's the code bit: 
I am playing with other mods, so this may just be a compat issue. 

[21:53:18] [Netty Local Client IO #0/ERROR]: Encountered exception while handling in channel with name "wildfire_gender:hurt"
java.lang.NoSuchMethodError: 'net.minecraft.class_1297 net.minecraft.class_1657.method_44329()'
	at Not Enough Crashes deobfuscated stack trace.(1.19.2+build.28) ~[?:?]
	at com.wildfire.main.WildfireEventHandler.lambda$registerClientEvents$2(WildfireEventHandler.java:131) ~[Female-Gender-Mod-fabric-1.19-3.0.0.jar:?]
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.receive(ClientPlayNetworkAddon.java:97) ~[fabric-networking-api-v1-1.2.5+c6af733c90-5612b0fd8966152f.jar:?]
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.receive(ClientPlayNetworkAddon.java:39) ~[fabric-networking-api-v1-1.2.5+c6af733c90-5612b0fd8966152f.jar:?]
	at net.fabricmc.fabric.impl.networking.AbstractChanneledNetworkAddon.handle(AbstractChanneledNetworkAddon.java:101) ~[fabric-networking-api-v1-1.2.5+c6af733c90-5612b0fd8966152f.jar:?]
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.handle(ClientPlayNetworkAddon.java:89) ~[fabric-networking-api-v1-1.2.5+c6af733c90-5612b0fd8966152f.jar:?]
	at net.minecraft.client.network.ClientPlayNetworkHandler.handler$bnj000$handleCustomPayload(ClientPlayNetworkHandler:2522) ~[?:?]
	at net.minecraft.client.network.ClientPlayNetworkHandler.onCustomPayload(ClientPlayNetworkHandler) ~[?:?]
	at net.minecraft.network.packet.s2c.play.CustomPayloadS2CPacket.apply(CustomPayloadS2CPacket:60) ~[?:?]
	at net.minecraft.network.packet.s2c.play.CustomPayloadS2CPacket.apply(CustomPayloadS2CPacket:8) ~[?:?]
	at net.minecraft.network.ClientConnection.handlePacket(ClientConnection:167) ~[?:?]
	at net.minecraft.network.ClientConnection.channelRead0(ClientConnection:152) ~[?:?]
	at net.minecraft.network.ClientConnection.channelRead0(ClientConnection:50) ~[?:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:299) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.local.LocalChannel.finishPeerRead0(LocalChannel.java:445) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.local.LocalChannel.access$400(LocalChannel.java:50) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.local.LocalChannel$5.run(LocalChannel.java:403) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) [netty-common-4.1.77.Final.jar:?]
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) [netty-common-4.1.77.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.77.Final.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[21:53:19] [Server thread/INFO]: Aojae lost connection: Internal Exception: java.nio.channels.ClosedChannelException

**Comment by GayRedPanda** [comment]
I'm not sure what version you are using, but
If you are on 3.0 or lower, the issue was fixed in 3.0.1
If you are using 3.0.1, then I'm not quite sure what it could be. Someone else would have to take a look.

**Comment by Kichura** [comment]
Your mod is outdated.

**Comment by AzureMonument** [comment]
Okay, got it from curseforge. Apparently the modrinth page only has 3.0.0 for some reason. Is the one on modrinth an unofficial upload?

**Comment by Kichura** [comment]
No, Modrinth is also an official place to upload mods to such as this one.

**Comment by WildfireRomeo** [comment]
Modrinth is official, I just lack updating it since I suck at remembering things.
