### ISSUE TITLE
female hurt sound v3.0.1 not working

### ISSUE THREAD

**Issue by KominoStyle** [WildfireRomeo/WildfireFemaleGenderMod#83]
on my first time the sound worked, after next time i started the game it wont work anymore, i even reinstalled the mod. nothing happend, i gonna miss the sound, it was perfect :)

**Comment by KominoStyle** [comment]
update, i found out it is not working on multiplayer only -.-!

**Comment by saavor** [comment]
for me it doent work in multiplayer and the game crashes in singleplayer. im not sure why its not working but it might be that i use quilt and not fabric.

the error:
```
[18:52:14] [Netty Local Client IO #0/ERROR]: Encountered exception while handling in channel with name "wildfire_gender:hurt"
java.lang.NoSuchMethodError: 'net.minecraft.class_1297 net.minecraft.class_1657.method_44329()'
	at com.wildfire.main.WildfireEventHandler.lambda$registerClientEvents$2(WildfireEventHandler.java:131) ~[Female-Gender-Mod-fabric-1.19-3.0.0.jar:?]
	at net.fabricmc.fabric.api.client.networking.v1.ClientPlayNetworking$PlayChannelHandler.receive(ClientPlayNetworking.java:214) ~[fabric-networking-api-v1-4.0.0-beta.19+0.64.0-1.19.2.jar-de8098e2-be71-43dc-a7f4-d6138ada3cab-nested.jar:?]
	at org.quiltmc.qsl.networking.impl.client.ClientPlayNetworkAddon.receive(ClientPlayNetworkAddon.java:100) ~[networking-3.0.0-beta.20+1.19.2.jar-fdf0aea8-57c5-441d-9044-d1eb0df511c6-nested.jar:?]
	at org.quiltmc.qsl.networking.impl.client.ClientPlayNetworkAddon.receive(ClientPlayNetworkAddon.java:41) ~[networking-3.0.0-beta.20+1.19.2.jar-fdf0aea8-57c5-441d-9044-d1eb0df511c6-nested.jar:?]
	at org.quiltmc.qsl.networking.impl.AbstractChanneledNetworkAddon.handle(AbstractChanneledNetworkAddon.java:101) [networking-3.0.0-beta.20+1.19.2.jar-fdf0aea8-57c5-441d-9044-d1eb0df511c6-nested.jar:?]
	at org.quiltmc.qsl.networking.impl.client.ClientPlayNetworkAddon.handle(ClientPlayNetworkAddon.java:92) [networking-3.0.0-beta.20+1.19.2.jar-fdf0aea8-57c5-441d-9044-d1eb0df511c6-nested.jar:?]
	at net.minecraft.class_634.handler$zma000$handleCustomPayload(class_634.java:2520) [client-intermediary.jar:?]
	at net.minecraft.class_634.method_11152(class_634.java) [client-intermediary.jar:?]
	at net.minecraft.class_2658.method_11457(class_2658.java:60) [client-intermediary.jar:?]
	at net.minecraft.class_2658.method_11054(class_2658.java:8) [client-intermediary.jar:?]
	at net.minecraft.class_2535.method_10759(class_2535.java:167) [client-intermediary.jar:?]
	at net.minecraft.class_2535.method_10770(class_2535.java:152) [client-intermediary.jar:?]
	at net.minecraft.class_2535.channelRead0(class_2535.java:50) [client-intermediary.jar:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:299) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.local.LocalChannel.finishPeerRead0(LocalChannel.java:445) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.local.LocalChannel.access$400(LocalChannel.java:50) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.local.LocalChannel$5.run(LocalChannel.java:403) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) [netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) [netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.77.Final.jar:4.1.77.Final]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```
